chore: handle integer maps in openapi (#694)
### Context
For objects that are maps having key as string and value as integer, the
open-api definition looks something like this:
```
schema_name:
    type: object
    additionalProperties:
      type: integer
```
This was not present in public specs till now. But now it is present in
one of the spec files
[here](https://code.hq.twilio.com/twilio/open-api/blob/f52384fce4c47d3c2d12ef70b39c6b860dd2d701/spec/insights/v2/schemas.yaml#L208).

### Error and its root cause
When something like this is processed by our generator, it throws the
following error:
```
java.util.regex.PatternSyntaxException: Illegal repetition
{ [key: string]: number; } occurs in NodeCodegenModelDataTypeResolver.java:66
```
This arises because when the Twilio Node generator processes
additionalProperties definitions as mentioned above, it generates
TypeScript-like type definitions such as:
 ` { [key: string]: number; }`

In NodeCodegenModelDataTypeResolver.java:66, this generated type string
is incorrectly used as a regex pattern in the replaceFirst() method:

 ```
consumer.accept(datatypeWithEnum, dataType.replaceFirst(baseType,
datatypeWithEnum));
```

  The problem is that { [key: string]: number; } contains curly braces {} which have special meaning in regex as quantifiers (e.g., {n} means "exactly n times"). However, the braces in `{ [key: string]: number; }` are not properly formatted as regex quantifiers, causing the "Illegal repetition" error.

### Solution

  The fix is to escape the baseType parameter before using it as a regex pattern with the help of Pattern.quote() method which treats the string as a literal pattern, escaping any regex special characters.

### Difference
The change is relevant for fluent api languages like node, python and ruby. However, as mentioned above, since we didn't have any string-to-int map till now in our open-api specs, the change does not create any difference in the existing helpers.

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [ ] Run `make test-docker`
- [ ] Verify affected language:
    - [ ] Generate [twilio-go](https://github.com/twilio/twilio-go) from our [OpenAPI specification](https://github.com/twilio/twilio-oai) using the [build_twilio_go.py](./examples/build_twilio_go.py) using `python examples/build_twilio_go.py path/to/twilio-oai/spec/yaml path/to/twilio-go` and inspect the diff
    - [ ] Run `make test` in `twilio-go`
    - [ ] Create a pull request in `twilio-go`
    - [ ] Provide a link below to the pull request
- [ ] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [ ] I have read the [Contribution Guidelines](https://github.com/twilio/twilio-oai-generator/blob/main/CONTRIBUTING.md) and my PR follows them
- [ ] I have titled the PR appropriately
- [ ] I have updated my branch with the main branch
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation about the functionality in the appropriate .md file
- [ ] I have added inline documentation to the code I modified

If you have questions, please create a GitHub Issue in this repository.